### ISSUE TITLE
is this repo deprecated in favour of https://nextjournal.com/sicm?

### ISSUE THREAD

**Issue by Quantisan** [sicmutils/sicm-exercises#11]

**Comment by sritchie** [comment]
Hey @Quantisan , it's not deprecated - I've just been busy enough over at https://github.com/sicmutils/sicmutils that I haven't worked on the book's exercises in quite some time!

I still think it's important to have a copy of exercises that can work in different environments, so at some point I plan on coming back here and getting everything into shape to be able to export to

- TeX PDF, to potentially produce a solutions manual
- nextjournal pages
- Clojure source files, so folks can use these with their favorite local editor

Happy to collaborate on any of this, or help out with anything you need, since I know that the Clojure branch is a bit stalled here.

Cheers,
Sam
